TensorCreator:
  FileParams:
    path_to_main_dir: "path_to_RawDataRelease"
  CreatorParams:
    translate_hex: true
    start_folder: "2009A"
    end_folder: "2011A"

DataAcquisitionChange:
  BeforePerigeeChange: 'o0127'
  AfterPerigeeChange: 'o0130a'

ChannelAnalyzer:
  hi_tensor_directory: "./output/AfterPerigeeChange/Hi_data"
  lo_tensor_directory: "./output/AfterPerigeeChange/Lo_data"
  output_dir: "./channel_analyzer_out_aggregated/AfterPerigeeChange"
  hi_instruction_file: "./instructions/HiCullGoodTimes.txt"
  lo_instruction_file: "./instructions/LoGoodTimes.txt"